--- arch/arm64/boot/dts/amlogic/Makefile
+++ arch/arm64/boot/dts/amlogic/Makefile
@@ -103,6 +103,7 @@ dtb-$(CONFIG_ARCH_MESON) += meson-sm1-khadas-vim3l.dtb
 dtb-$(CONFIG_ARCH_MESON) += meson-sm1-odroid-c4.dtb
 dtb-$(CONFIG_ARCH_MESON) += meson-sm1-odroid-hc4.dtb
 dtb-$(CONFIG_ARCH_MESON) += meson-sm1-sei610.dtb
+dtb-$(CONFIG_ARCH_MESON) += meson-sm1-skyworth-lb2004-a4091.dtb
 dtb-$(CONFIG_ARCH_MESON) += meson-sm1-tx3-bz.dtb
 dtb-$(CONFIG_ARCH_MESON) += meson-sm1-tx3-bz-oc.dtb
 dtb-$(CONFIG_ARCH_MESON) += meson-sm1-tx3-qz.dtb
